
input_topic: "zed/point_cloud/cloud_registered/limitcloud"
# Robot width in meters
width: 0.55
# Robot length in meters
length: 0.65
# Tolerance in width and length
tolerance: 0.20

# Points in the cloud to slide
slide_x: 20
slide_y: 20

# Yellow
red_value: 255
green_value: 255
blue_value: 0